python step0.py --llm 'llama' --train_dataset 'hotpotqa'
python step1.py --llm 'llama' --train_dataset 'hotpotqa'
python step0.py --llm 'llama' --train_dataset 'musique'
python step1.py --llm 'llama' --train_dataset 'musique'
python step0.py --llm 'llama' --train_dataset '2wikimqa'
python step1.py --llm 'llama' --train_dataset '2wikimqa'

python step0.py --llm 'mistral' --train_dataset 'hotpotqa'
python step1.py --llm 'mistral' --train_dataset 'hotpotqa'
python step0.py --llm 'mistral' --train_dataset 'musique'
python step1.py --llm 'mistral' --train_dataset 'musique'
python step0.py --llm 'mistral' --train_dataset '2wikimqa'
python step1.py --llm 'mistral' --train_dataset '2wikimqa'

python step0.py --llm 'qwen' --train_dataset 'hotpotqa'
python step1.py --llm 'qwen' --train_dataset 'hotpotqa'
python step0.py --llm 'qwen' --train_dataset 'musique'
python step1.py --llm 'qwen' --train_dataset 'musique'
python step0.py --llm 'qwen' --train_dataset '2wikimqa'
python step1.py --llm 'qwen' --train_dataset '2wikimqa'